/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessControl } from "./AccessControl";
export type { ERC165 } from "./ERC165";
export { AccessControl__factory } from "./factories/AccessControl__factory";
export { ERC165__factory } from "./factories/ERC165__factory";
export { IAccessControl__factory } from "./factories/IAccessControl__factory";
export { IERC165__factory } from "./factories/IERC165__factory";
export { WillFactory__factory } from "./factories/WillFactory__factory";
export { Will__factory } from "./factories/Will__factory";
export type { IAccessControl } from "./IAccessControl";
export type { IERC165 } from "./IERC165";
export type { Will } from "./Will";
export type { WillFactory } from "./WillFactory";
